### ISSUE TITLE
冬至重复

### ISSUE THREAD

**Issue by zheyi420** [KaitoHH/24-jieqi-ics#1]
在官方的“中国节假日”订阅中，冬至现也已显示，因而产生重复。

**Comment by KaitoHH** [comment]
我目前好像还没有发现中国节假日中多了冬至，如果后续冬至确实已显示，我会考虑将其删除。

你目前也可以先自行修改ics文件，比如可以先用如下的正则直接将所有的冬至节气匹配删除。
```regex
(.*\n){6}SUMMARY:立冬\nEND:VEVENT\n
```

**Comment by KaitoHH** [comment]
实测：官方的中国节假日现在会显示全部的节气了，因此两者选一即可。
