### ISSUE TITLE
使用方法2订阅了之后没有在Mac的日历上显示

### ISSUE THREAD

**Issue by chennobody** [KaitoHH/24-jieqi-ics#2]
型号与配置及显示如下图所示：
![image](https://user-images.githubusercontent.com/22138217/106745934-c4d12f80-665c-11eb-9464-bdff57236f0c.png)
![image](https://user-images.githubusercontent.com/22138217/106746380-6eb0bc00-665d-11eb-8e88-9ef2e06461de.png)
![image](https://user-images.githubusercontent.com/22138217/106746397-74a69d00-665d-11eb-9c61-d103dbd5c011.png)

**Comment by KaitoHH** [comment]
试了一下是正常的，请检查一下是否是订阅的日历太多导致没有完全显示。
