### ISSUE TITLE
没有清明的问题

### ISSUE THREAD

**Issue by wangyuanpeng5e** [KaitoHH/24-jieqi-ics#4]
您好，看了一下，好像没有清明这个节气噢

**Comment by wangyuanpeng5e** [comment]
抱歉。没看到简介。请问有没有办法手动添加清明节气呢，感谢!

**Comment by kevinjobs** [comment]
> 抱歉。没看到简介。请问有没有办法手动添加清明节气呢，感谢!

可以用文本编辑器打开文件，里面格式比较简单，可以参照自己写一下

**Comment by wangyuanpeng5e** [comment]
好的，感谢
